# This is a basic workflow to help you get started with Actions

name: List Check
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  # Trigger on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/15 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #
      - name: Run Sript
        run: |
          chmod +x ./scripts/active-list.sh
          ./scripts/active-list.sh

      - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: "adblock-bad.txt"

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Vuong

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: 3781991+kinekt4@users.noreply.github.com

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
          # branch: some-branch

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          # cwd: "./path/to/the/repo"

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "List Check (automated)"

          # The flag used on the pull strategy
          # Default: '--no-rebase'
          # pull_strategy: "--no-rebase or --no-ff or --rebase"

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          # remove: "./dir/old_file.js"

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
          # signoff: true

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          # tag: "v1.0.0 --force"

        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
